# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodfit-deployment
  labels:
    app: foodfit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodfit
  template:
    metadata:
      labels:
        app: foodfit
    spec:
      containers:
      - name: foodfit
        image: yourdockerhubusername/foodfit:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: foodfit-service
spec:
  selector:
    app: foodfit
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
