apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-tracker-deployment
  labels:
    app: fitness-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-tracker
  template:
    metadata:
      labels:
        app: fitness-tracker
    spec:
      containers:
      - name: fitness-tracker
        image: siddhartha9/fitness-tracker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fitness-tracker-service
spec:
  type: NodePort
  selector:
    app: fitness-tracker
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
